import { collection, addDoc, doc, onSnapshot, query, where, orderBy, serverTimestamp, getDocs } from 'firebase/firestore';
import { deleteObject, getDownloadURL, ref, uploadBytesResumable } from 'firebase/storage';
import { db, storage, firebaseEnabled } from '../firebase/config';
const requireFirebase = () => { if (!firebaseEnabled) throw new Error('Firebase is not configured. Add frontend/.env values first.'); };
export async function uploadDocument(file, userId, onProgress = () => {}) { requireFirebase(); if (!['application/pdf','image/jpeg','image/png'].includes(file.type)) throw new Error('Only PDF, JPG and PNG files are supported.'); if (file.size > 10 * 1024 * 1024) throw new Error('File must be 10 MB or smaller.'); const objectRef = ref(storage, `documents/${userId}/${crypto.randomUUID()}-${file.name}`); return new Promise((resolve, reject) => { const task = uploadBytesResumable(objectRef, file, { contentType: file.type }); task.on('state_changed', (snap) => onProgress(Math.round(snap.bytesTransferred / snap.totalBytes * 100)), reject, async () => resolve({ name: file.name, size: file.size, type: file.type, path: objectRef.fullPath, url: await getDownloadURL(task.snapshot.ref) })); }); }
export async function createOrder(payload) { requireFirebase(); return addDoc(collection(db, 'orders'), { ...payload, status: 'placed', paymentStatus: 'pending', createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); }
export function listenToUserOrders(uid, callback) { requireFirebase(); const q = query(collection(db, 'orders'), where('customerId','==',uid), orderBy('createdAt','desc')); return onSnapshot(q, (snap) => callback(snap.docs.map((item) => ({ id: item.id, ...item.data() })))); }
export function listenToShopOrders(shopId, callback) { requireFirebase(); const q = query(collection(db, 'orders'), where('shopId','==',shopId), orderBy('createdAt','desc')); return onSnapshot(q, (snap) => callback(snap.docs.map((item) => ({ id: item.id, ...item.data() })))); }
export { db, doc, getDocs, serverTimestamp, addDoc, collection, firebaseEnabled, deleteObject, ref };
